### ISSUE TITLE
`fs-storage`: Update FileStorage format

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ark-rust#38]
We have mixed format now:
* `version 2` came from the legacy plain-text format
* the mapping itself is presented as JSON

```
$ cargo run --example cli write /tmp/test a:1,b:2

$ cat /tmp/test | jq
version 2
{"a":"1","b":"2"}
```

This makes the format not so ergonomic, power users need to perform extra step to remove the header:
```
$ tail -1 /tmp/test | jq 
{
  "a": "1",
  "b": "2"
}
```

It's better to complete transition to JSON.

### Option 1: "Flat syntax"
If we declare `version` in the mapping itself, we'd need to handle it as a special field before reading the entries:
```
{
    "a":"1",
    "b":"2",
    "version":"3"
}
```

Can it cause problems when we expect non-string keys in the storage? E.g. with the following storage:
```
{
    "1":"a",
    "2":"b",
    "version":"3"
}
```

### Option 2: "Nested syntax"
We can use the nested JSON structure, where top-level always consists of 2 fields: `version`, and `entries`. The latter lists all key-values inside:
```
{
    "version":"3",
    "entries": {
        "1":"a",
        "2":"b"
    }
}
```

This format is explicit, no type inconsistencies but the format is more verbose.

**Comment by tareknaser** [comment]
I prefer the second option, nested syntax. It seems very clear to me
also a user might include a key-value pair where the key is the word "version"

**Comment by tareknaser** [comment]
It'll also make data extraction easier since we won't have to exclude the entry with the key "version"
